server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true #sql 출력
    properties:
      hibernate:
        format_sql: true # sql 이쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 제한

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10mb로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기 합을 100MB로 제한

  thymeleaf:
    cache: false
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000 # 5초


kakao:
  client:
    id: 7b9f2d7cea2e70647d9f27cbfa0c3916
    secret: 0r1czyG7w7h1HAC9qix2MEqmELm2cCJ2

token:
  secret: and0LXRva2VuLXNlY3JldA== # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)
