server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true #sql 출력
    properties:
      hibernate:
        format_sql: true # sql 이쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 제한

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10mb로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기 합을 100MB로 제한

  thymeleaf:
    cache: false
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
